namespaces:
  git:
    commands:
      commit:
        command: git commit -m "{{ message }}" --trailer "Relates-To={{ issue }}"
        description: git commit
        parameters:
          message:
            prompt: "Enter commit message"
          issue:
            default: "#123"
  other:
    commands:
      that:
        command: "echo '{{ world }}'"
        description: "This is some amazing stuff"
        tags:
        - tag1
        - tag2
        parameters:
          world:
            prompt: "Enter world"
            default: "World"
            choices:
            - test
            - other test
            exclusive: true
            mapping:
              test: "this gets returned"

config:
  shell: bash
